// ----------------------------------------------------------------------

export const program = [
  'ARECAS Confort',
  'ARECAS Elite',
  'ARECAS Dream',
  'ARECAS Premium',
  'ARECAS Gold',
  'ARECAS Millesime',
  'ARECAS Millesime Plus',
  'ARECAS Planitium',
  'ARECAS Planitium Plus',
  'ARECAS Privilège F5',
  'ARECAS Privilège F5 Plus',
  'ARECAS Privilège F6 Plus',
  'ARECAS Privilège F7',
  'ARECAS Privilège F7 Plus',
  'ARECAS Privilège F8',
  'ARECAS Privilège F8 Plus',
  'ARECAS Privilège F9',
  'ARECAS Privilège F9 Plus',
  'ARECAS Privilège F10',
  'ARECAS Privilège F10 Plus',
  'ARECAS Privilège F11',
  'ARECAS Privilège F11 Plus',
  'ARECAS Privilège F12',
  'ARECAS Privilège F12 Plus',
  'ARECAS Privilège F13',
  'ARECAS Privilège F13 Plus',
  'ARECAS Privilège F14',
  'ARECAS Privilège F14 Plus',
  'ARECAS Privilège F15',
  'ARECAS Privilège F15 Plus',
  'ARECAS Privilège F16',
  'ARECAS Privilège F16 Plus',
  'ARECAS Privilège F17',
  'ARECAS Privilège F17 Plus',
  'ARECAS Privilège F18',
  'ARECAS Privilège F18 Plus',
  'ARECAS Privilège F19',
  'ARECAS Privilège F19 Plus',
  'ARECAS Privilège F20',
  'ARECAS Privilège F20 Plus',
  'ARECAS Privilège F21',
  'ARECAS Privilège F21 Plus',
  'ARECAS Privilège F22',
  'ARECAS Privilège F22 Plus',
  'ARECAS Privilège F23',
  'ARECAS Privilège F23 Plus',
  'ARECAS Privilège F24',
  'ARECAS Privilège F24 Plus',
  'ARECAS Privilège F25',
  'ARECAS Privilège F25 Plus',
  'ARECAS Privilège F26',
  'ARECAS Privilège F26 Plus',
  'ARECAS Privilège F27',
  'ARECAS Privilège F27 Plus',
  'ARECAS Privilège F28',
  'ARECAS Privilège F28 Plus',
  'ARECAS Privilège F29',
  'ARECAS Privilège F29 Plus',
];
